on:
  tags: true

sudo: required

services:
  - docker

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"

script:
  - ALPINE_IMGID=$(docker build -t "carbonsrv/carbon:${TRAVIS_TAG:-latest}" -f Dockerfile . | tee /dev/stderr | tail -1 | sed 's/.*Successfully built \(.*\)$/\1/') # Build with Alpine
  - docker export $ALPINE_IMGID | docker import - "carbonsrv/carbon:${TRAVIS_TAG:-latest}-alpine"
  - ALPINE_CNTID=$(docker run -d --entrypoint /bin/sh "carbonsrv/carbon:${TRAVIS_TAG:-latest}" true) # Flattening of Alpine image
  - docker export $ALPINE_CNTID | docker import – "carbonsrv/carbon:${TRAVIS_TAG:-latest}"
  - docker export $ALPINE_CNTID | docker import – "carbonsrv/carbon:${TRAVIS_TAG:-latest}-alpine"
  - docker rm $ALPINE_CNTID

  - ALPINE_EDGE_IMGID=$(docker build -t "carbonsrv/carbon:${TRAVIS_TAG:-latest}" -f Dockerfile . | tee /dev/stderr | tail -1 | sed 's/.*Successfully built \(.*\)$/\1/') # Build with Alpine Edge
  - ALPINE_EDGE_CNTID=$(docker run -d --entrypoint /bin/sh "carbonsrv/carbon:${TRAVIS_TAG:-latest}-alpine-edge" true) # Flattening of Alpine Edge image
  - docker export $ALPINE_EDGE_CNTID | docker import – "carbonsrv/carbon:${TRAVIS_TAG:-latest}-alpine-edge"
  - docker rm $ALPINE_EDGE_CNTID

  - ARCH_IMGID=$(docker build -t "carbonsrv/carbon:${TRAVIS_TAG:-latest}-arch" -f Dockerfile.arch . | tee /dev/stderr | tail -1 | sed 's/.*Successfully built \(.*\)$/\1/') # Build with Arch
  - ARCH_CNTID=$(docker run -d --entrypoint /bin/sh "carbonsrv/carbon:${TRAVIS_TAG:-latest}-arch" true) # Flattening of Arch image
  - docker export $ARCH_CNTID | docker import – "carbonsrv/carbon:${TRAVIS_TAG:-latest}-arch"
  - docker rm $ARCH_CNTID

  - GOLANG_IMGID=$(docker build -t "carbonsrv/carbon:${TRAVIS_TAG:-latest}-golang" -f Dockerfile.golang . | tee /dev/stderr | tail -1 | sed 's/.*Successfully built \(.*\)$/\1/') # Build with Golang
  - GOLANG_CNTID=$(docker run -d --entrypoint /bin/sh "carbonsrv/carbon:${TRAVIS_TAG:-latest}-golang" true) # Flattening of Arch image
  - docker export $GOLANG_CNTID | docker import – "carbonsrv/carbon:${TRAVIS_TAG:-latest}-golang"
  - docker rm $GOLANG_CNTID

after_success:
  - docker push carbonsrv/carbon
