language: go

go:
  - 1.3
  - 1.4
  - 1.5
  - tip

addons:
  apt:
    packages:
      - libluajit-5.1-dev
      - libphysfs-dev

notifications:
  irc:
    channels:
      - "irc.esper.net#vifino"
      use_notice: true
