on:
  tags: true

sudo: required

services:
  - docker

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"

script:
  - ALPINE_ID=$(docker build -t "carbonsrv/carbon:${TRAVIS_TAG:-latest}" -f Dockerfile . | tee /dev/stderr | tail -1 | sed 's/.*Successfully built \(.*\)$/\1/') # Build with Alpine
  - docker export $ALPINE_ID | docker import - "carbonsrv/carbon:${TRAVIS_TAG:-latest}-alpine"
  - docker tag $ALPINE_ID "carbonsrv/carbon:${TRAVIS_TAG:-latest}-alpine"

  - ALPINE_EDGE_ID=$(docker build -t "carbonsrv/carbon:${TRAVIS_TAG:-latest}" -f Dockerfile . | tee /dev/stderr | tail -1 | sed 's/.*Successfully built \(.*\)$/\1/') # Build with Alpine Edge
  - docker export $ALPINE_EDGE_ID | docker import - "carbonsrv/carbon:${TRAVIS_TAG:-latest}-alpine-edge"

  - ARCH_ID=$(docker build -t "carbonsrv/carbon:${TRAVIS_TAG:-latest}-arch" -f Dockerfile.arch . | tee /dev/stderr | tail -1 | sed 's/.*Successfully built \(.*\)$/\1/') # Build with Arch
  - docker export $ARCH_ID | docker import - "carbonsrv/carbon:${TRAVIS_TAG:-latest}-arch"

  - GOLANG_ID=$(docker build -t "carbonsrv/carbon:${TRAVIS_TAG:-latest}-golang" -f Dockerfile.golang . | tee /dev/stderr | tail -1 | sed 's/.*Successfully built \(.*\)$/\1/') # Build with Arch
  - docker export $GOLANG_ID | docker import - "carbonsrv/carbon:${TRAVIS_TAG:-latest}-golang"

after_success:
  - docker push carbonsrv/carbon
